// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNlrKTH5tQj6yhE6wpxlgAkDsIbE7t8k',
    appId: '1:884664782421:web:3472818288a534bacc0edc',
    messagingSenderId: '884664782421',
    projectId: 'meow-movies',
    authDomain: 'meow-movies.firebaseapp.com',
    storageBucket: 'meow-movies.appspot.com',
    measurementId: 'G-QDBCC46JHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUXubzePY5DIJgorVwz3k6Uzgz0zLck0',
    appId: '1:884664782421:android:60e46d8dc7989395cc0edc',
    messagingSenderId: '884664782421',
    projectId: 'meow-movies',
    storageBucket: 'meow-movies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhNL5rA2cCfoC_blWNbpi3rsDipaSAlv8',
    appId: '1:884664782421:ios:be0879595a00e2b7cc0edc',
    messagingSenderId: '884664782421',
    projectId: 'meow-movies',
    storageBucket: 'meow-movies.appspot.com',
    iosClientId: '884664782421-m87mb0vakvo0a1vm6ililo18mkkrl6mp.apps.googleusercontent.com',
    iosBundleId: 'com.example.meowFilms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhNL5rA2cCfoC_blWNbpi3rsDipaSAlv8',
    appId: '1:884664782421:ios:c2f931cea12faa3ccc0edc',
    messagingSenderId: '884664782421',
    projectId: 'meow-movies',
    storageBucket: 'meow-movies.appspot.com',
    iosClientId: '884664782421-k5e3spueav6qmvcavrivd5ud4vjcpseo.apps.googleusercontent.com',
    iosBundleId: 'com.example.meowFilms.RunnerTests',
  );
}
